### ISSUE TITLE
Publish/Subscribe mechanism.

### ISSUE THREAD

**Issue by sidneycadot** [teamdiamond/qmi#11]
We'd like a mechanism to support some type of publish subscribe mechanism, a.k.a.

- observer/observable
- one-to-many
- signal/slot

**Comment by sidneycadot** [comment]
Consider receiver-side fifo's (with "missing packets" indication).

**Comment by jorisvr** [comment]
Could be useful for PtGrey_BlackFly camera (publishing acquired images).

**Comment by sidneycadot** [comment]
![image](https://user-images.githubusercontent.com/3049380/49143840-36362a80-f2fc-11e8-9267-297c9833ec36.png)

**Comment by sidneycadot** [comment]
Decision:
- contexts will receive subscription messages on behalf of local receivers, and distribute them locally.
- we will use receiver objects that buffer incoming data to facilitate single-threaded tasks.
- throttling may be handled by XON/XOFF like traffic between contexts. Alternative is some kind of 'drop oldest message' policy. This is for a later stage, let's get a basic version up&running first.

Joris will work on a first version.

**Comment by jorisvr** [comment]
First version implemented, see branch dev_pubsub 048bdcc1a064a51f5578cb90916886a592e5234c

NOT YET TESTED

**Comment by sidneycadot** [comment]
Test available and merged into master.

Now we will start using it and update functionality if needed.
