### ISSUE TITLE
(Re-)define logging policy.

### ISSUE THREAD

**Issue by jorisvr** [teamdiamond/qmi#17]
Currently logging depends on environment variable QMI_JORIS. This seems non-sensical.

It may be nice to enable logging to screen for INFO and higher levels by default.
Then optionally override log levels based on a configuration file.

May also be nice to automatically log to a file.

Also consider initializing logging at `qmi.start()` instead of `import qmi`.
This makes sense because `qmi.start()` is probably also the point where configuration files are processed etc.

**Comment by sidneycadot** [comment]
Think about what 'import qmi' does for logging.

**Comment by jorisvr** [comment]
New policy (already implemented in master branch):
* `import qmi` does not affect the logging policy.
* `qmi.start()` sets up a default logging policy:
  * start logging to stderr at level WARNING (log level can be specified in configuration file)
  * start logging to a file `qmi.log` (file name can be specified in configuration file)
  * set default log level to INFO (log level can be specified in configuration file, global and per logger)
  * configure the `warnings` module to redirect all warning to the logging system
  * set up a global exception hook to log uncaught exceptions
* If the environment variable `QMI_DEBUG` is set, the logging policy changes as follows:
  * `import qmi` already starts logging to stderr (to enable debugging of early initialization)
  * log level is set to DEBUG, overriding levels set in the configuration file
