### ISSUE TITLE
Design QMI configuration file structure.

### ISSUE THREAD

**Issue by jorisvr** [teamdiamond/qmi#18]
Things we may need from the configuration file:
 - IP addresses and ports of other contexts.
 - TCP server port to listen on for our context.
 - List of contexts to connect to at startup.
 - Workgroup name.
 - Log levels and log configuration.
 - IP addresses / ports / settings of instruments.
 - ...

**Comment by sidneycadot** [comment]
We're converging on JSON-with-comments. Fine by me!

**Comment by jorisvr** [comment]
New approach:
* `qmi.start()` reads the configuration file.
  The location of the file is determined as follows:
  * specified as an argument to `qmi.start()`, or
  * taken from environment variable `QMI_CONFIG`, or
  * default to `$HOME/qmi.conf`.
* The parsed configuration data is managed by the QMI_Context object.
* The configuration file contains a list of peer contexts to connect to; this is handled by `qmi.start()`.
