### ISSUE TITLE
Decide and document precise behavior of Transport methods

### ISSUE THREAD

**Issue by sidneycadot** [teamdiamond/qmi#27]
In particular, I want to discuss the desirable behavior of the methods in case of timeouts.

**Comment by jorisvr** [comment]
`QMI_Treansport.read()` and `QMI_Transport.read_until()` must raise exception in case of timeout instead of returning partial data.

In addition, we can make a separate method `QMI_Transport.read_until_timeout()`.

**Comment by jorisvr** [comment]
Done - commit 803e971b757449766c3afd1a48e7636bdff4d20c

`QMI_Transport.read()` and `QMI_Transport.read_until()` now raise exception in case of timeout and leave partial data in an internal read buffer.
New method `QMI_Transport.read_until_timeout()` has the previous semantics of `QMI_Transport.read()`.
