### ISSUE TITLE
Make QMI driver for Tektronix frequency counter

### ISSUE THREAD

**Issue by jorisvr** [teamdiamond/qmi#35]
Interface is USBTMC (USB test & measurement).

First attempt to control with pyvisa failed. To be investigated.

**Comment by jorisvr** [comment]
Access via pyvisa now works.

Note 1: The USB interface must be manually enabled on the instrument front panel.
Note 2: To allow user access to the instrument on Linux, a statement must be added to /etc/udev/rules.d/usbtmc.rules.

The "MEAS:FREQ?" command may fail to answer within the default query timeout, causing an exception in pyvisa. Perhaps longer timeout should be specified, depending on mode of operation etc.

**Comment by jorisvr** [comment]
Note: We are temporarily testing with a Tektronix FCA3000 counter, but the final solution will be based on a Pendulum CNT91 counter.

The programming interface of the Pendulum counter is believed to be compatible with Tektronix FCA3100 and mostly compatible with Tektronix FCA3000.

**Comment by jorisvr** [comment]
Done 0987b0b400ebc3f645f40dad72afe654b2ed76e8

Currently only supports get_frequency()
more advanced commands to be implemented as needed.

Note the USB connection tends to crash when an incorrect command is sent via PyVISA-py. To be investigated at USBTMC level.

**Comment by sidneycadot** [comment]
Closing, we have a working driver.
