### ISSUE TITLE
RpcObjects must have a name, but they don't have an __init__() where it is set.

### ISSUE THREAD

**Issue by sidneycadot** [teamdiamond/qmi#38]

**Comment by jorisvr** [comment]
Fixed. d50436dbf98f58b0fe5530dec11fb81c89276197

* QMI_RpcObject constructor is now:
`def __init__(self, context: 'qmi.core.context.QMI_Context', name: str)`
* QMI_RpcObject instances have private attributes `_context` and `_name`.
* The name is identical to the "object_id" part of the address for RPC queries.
* To create an RpcObject, one should now call:
`context.make_rpc_object("object_name", ObjectClass, args...)`
(i.e. no more lambda function)
