### ISSUE TITLE
Talker-only mode for Pendulum

### ISSUE THREAD

**Issue by sidneycadot** [teamdiamond/qmi#41]
We accidentally got a Pendulum CNT-90 instead of a Pendulum CNT-91. Wait for the CNT-91 until we retry our talker-only experiment.

**Comment by sidneycadot** [comment]
Joris is trying to get it to work.

**Comment by jorisvr** [comment]
Our attempts to enable Talk Only mode via USB fail.
As soon as we send "SYST:TALK 1", the instrument spontaneously disconnects from USB and reattaches.
Subsequent "SYST:ERR?" query results in -221,"Settings conflict".
We think we covered all "prerequisites" listed in the programmer handbook (DISP:ENAB OFF, FORM PACK, INIT:CONT ON).

Without Talk Only mode, we can measure frequency at about 70 measurements/second.

We sent an email to Pendulum to ask for support.

**Comment by sidneycadot** [comment]
Joris is looking into this. It doesn't seem this is possible with frequency measurements, and the performance we get without talker-only mode now seems sufficient.

About to be closed, as far as I am concerned, but I'll leave this to Joris.

**Comment by jorisvr** [comment]
We emailed the Pendulum service department.
They confirm that Talk Only mode is NOT functional with USB.

Without talk only mode, we can measure average frequency at 70 meas/sec, or back-to-back frequency with reduced accuracy at 280 meas/sec. That is probably sufficient for us.
