### ISSUE TITLE
Group 'usbtmc'

### ISSUE THREAD

**Issue by sidneycadot** [teamdiamond/qmi#44]
Wie of wat maakt die aan?

**Comment by jorisvr** [comment]
De systeembeheerder maakt die groep met de hand aan tijdens installatie:
`$ sudo addgroup usbtmc`
`$ sudo adduser qinc usbtmc`

**Comment by sidneycadot** [comment]
We need to move the node setup docs to the qinc repo. Closing this issue and opening an issue for that.
