### ISSUE TITLE
Develop, check, and roll out idiom for dependencies in instrument drivers.

### ISSUE THREAD

**Issue by sidneycadot** [teamdiamond/qmi#46]
In instrument drivers, it may be the case that modules that are imported are not available which are used to drive the actual hardware.

Usually, one would just fail at import. However, we are in a situation where a client of an instrument may use a module to control a remote instrument, and there the non-availability of the module should not cause a problem.

**Comment by jorisvr** [comment]
Solved - commit bab037e40f15de8be06545d2a37f46c3fdf54f8c
