### ISSUE TITLE
Make and enforce policy for __del__ methods.

### ISSUE THREAD

**Issue by sidneycadot** [teamdiamond/qmi#48]

**Comment by jorisvr** [comment]
Decision (Sidney + Joris):
* `__del__()` methods should generally be avoided.
* `__del__()` methods should not be used to automatically close an instrument during cleanup. Such cleanup attempts may have unforeseen consequences with respect to multi-threading and during shutdown of the Python interpreter.
* `__del__()` methods should not even be used to warn against unclosed instruments.
* Existing `__del__()` methods with such purposes as described above, will be removed.
* `__del__()` methods may still be used for essential purposes other than automatically closing stuff.

**Comment by jorisvr** [comment]
Done. See commit b93400d09d28a4feccda744faf0a486026f407b6
