### ISSUE TITLE
Make atexit handler to warn about unstopped contexts at shutdown time.

### ISSUE THREAD

**Issue by sidneycadot** [teamdiamond/qmi#49]

**Comment by jorisvr** [comment]
Decision (Sidney + Joris):
* A new atexit handler will be created to print a warning when there are unstopped contexts. This will be implemented by maintaining a global counter of active contexts.
* The atexit handler will not attempt to call `qmi.stop()` on such contexts.
* The existing atexit handler which attempts to join remaining QMI_Threads will be removed.
* All QMI_Threads will be "daemon-threads" at Python level (i.e. the current implementation will be kept). This is necessary to avoid hangups when a program ends without cleaning up its threads (#45).

**Comment by jorisvr** [comment]
Done. See commit c5a2fbedcb5b2640ca1c4104d0899b1556a603c3
