### ISSUE TITLE
Consider Python context managers for QMI.start() and Instrument.open()

### ISSUE THREAD

**Issue by jorisvr** [teamdiamond/qmi#52]
Every code fragment that starts with `qmi.start()`, must logically end with `qmi.stop()`.

One way to do this is to simply ensure that the statements are paired up in the code.
However, to deal with exceptions and other non-local exits, it will often be necessary to use `try ... finally`.

Alternatively, we could use a Python `with` statement and a context manager which automatically stops the QMI context on exit from the `with` context:
```python
with qmi.start("context_name"):
    ... code ...
# qmi.stop() will be performed automatically at this point
```

A similar structure could be used for open/close of instruments, and perhaps for start/stop of tasks.

**Comment by sidneycadot** [comment]
Implemented context managers 'start_stop' and 'open_close' in qmi.utils.contextmanagers.

This should do for now.
