### ISSUE TITLE
Make ScpiProtocol class

### ISSUE THREAD

**Issue by jorisvr** [teamdiamond/qmi#57]
Many of our QMI instrument drivers implement write() / read() / ask() methods to talk to SCPI instruments. The implementation of these methods is essentially the same in all these drivers.

To reduce useless code duplication, we should make a `ScpiProtocol` class which implements these methods. Each SCPI-based instrument driver can then create an instance of this class.

This class should provide approximately the following interface:
```
class ScpiProtocol:
    def __init__(self, transport: QMI_Transport)
    def write(self, cmd: str)
    def read(self) -> str
    def ask(self, cmd: str) -> str
    def read_binary(self) -> bytes
```

**Comment by jorisvr** [comment]
To do:
* Use ScpiProtocol class where appropriate.

**Comment by sidneycadot** [comment]
Done.
