### ISSUE TITLE
Decide what to do with ArgumentParser

### ISSUE THREAD

**Issue by qraa** [teamdiamond/qmi#67]
*Resolution:*
* ArgumentParser() to be used as intended (document each argument via ArgumentParser separately).
* Docstring in main program serves to document the code, not for usage documentation.

*To do:*
* Change existing tools. code accordingly

*Placeholder ticket*

This is not the same. The `description` is meant to be a single paragraph describing the program; and command-line options to be documented in a different way.

I prefer to have a complete usage instruction in the docstring at the top of the main program. This does not match the philosophy of ArgumentParser, therefore I work around by overriding the two formatting methods. We can have a discussion about the best way to handle argument parsing and help texts in QMI. But I don't think this change is ok in the scope of type annotations.

_Originally posted by @jorisvr in https://github.com/teamdiamond/qmi/pull/64_

**Comment by jorisvr** [comment]
Done (commit 62dcdc43f382fe8ea244aa2479d6968a9226c396).
Existing tools adapter to use built-in help mechanism of ArgumentParser.
